const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "INEO",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Protestos",
            "description": "Endpoints",
        },
        {
            "name": "Emoluendos",
            "description": "Endpoints",
        },
        {
            "name": "Usuários",
            "description": "Endpoints",
        }
    ],
    definitions: {
        Users: {
            email: "marcelo@gmail.com",
            name: "Marcelo",
            password: "senha123",
        },
        AddUsers: {
            $email: "marcelo@gmail.com",
            $name: "Marcelo",
            $password: "senha123",
        },
        EditUser: {
            model: "Roberto",
        },
        Protests: {
            user_id: "1231242",
            debt: 5000,
            description: "descrição",
        },
        AddProtests: {
            $user_id: "1231242",
            $debt: 5000,
            $description: "descrição",
        },
        EditProtest: {
            debt: 3999,
        },
        Fees: {
            user_id: "1231242",
            protest_id: "23423525",
            protest_fee: 50,
        },
        AddFees: {
            $user_id: "1231242",
            protest_id: "23423525",
            protest_fee: 50,
        },
        EditFee: {
            protest_fee: 3999,
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/server.js')
})
