const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/app.js']

const doc = {
    info: {
        version: "1.0.0",
        title: "INEO",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Protestos",
            "description": "Endpoints",
        },
        {
            "name": "Emoluendos",
            "description": "Endpoints",
        },
        {
            "name": "Usuários",
            "description": "Endpoints",
        }
    ],
    definitions: {
        Vehicles: {
            maker: "Ford",
            year: 2013,
            model: "Fiesta",
            color: "White"
        },
        AddVehicles: {
            $maker: "Ford",
            $year: 2013,
            $model: "Fiesta",
            $color: "White"
        },
        EditVehicles: {
            model: "Mustang",
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/server.js')
})
